<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Service\AuthUserDetails'              => __DIR__ . '/Service/AuthUserDetails.php',
    'Application\Service\UserAccessChecker'            => __DIR__ . '/Service/UserAccessChecker.php',
    'RegistrationForm'                                 => __DIR__ . '/forms/RegistrationForm.php',
    'LoginForm'                                        => __DIR__ . '/forms/LoginForm.php',
    'Application\Module'                               => __DIR__ . '/Module.php',
    'Application\Authentication\AuthenticationService' => __DIR__ . '/src/Application/Authentication/AuthenticationService.php',
    'AuthController'                                   => __DIR__ . '/src/Application/Controller/AuthController.php',
    'Application\Controller\IndexController'           => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Users'                                            => __DIR__ . '/src/Application/model/Users.php',
);
