<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
        'template_map' => array(
            'layout/custom' => __DIR__ . '/../view/layout/custom.phtml',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'Chat\Controller\Index' => 'Chat\Controller\IndexController',
        ),

    ),

    'service_manager' => array(

    ),

    'router' => array(
        'routes' => array(
            'chat' => array(
                'type' => 'Literal',
                'options' => array(
                    'route' => '/chat',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Chat\Controller',
                        'controller' => 'Index',
                        'action' => 'index',
                    )
                )
            )
        ),
        'may_terminate' => true,
        'child_routes' => array(
            'default' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/[:controller[/:action]]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                    )
                )
            )
        )
    )
);