<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 6/17/15
 * Time: 9:11 AM
 */
use ZfcUser\View\Helper\ZfcUserIdentity;
?>

ID: <?php echo $this->zfcUserIdentity()->getId(); ?>&nbsp;&nbsp;
Nick: <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>&nbsp;&nbsp;
Email: <?php echo $this->zfcUserIdentity()->getEmail() ?>&nbsp;&nbsp;
Username: <?php echo $this->zfcUserIdentity()->getUsername(); ?>&nbsp;&nbsp;

<br><br><br><br><br><br>
שלום <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> !<br><br>

ברוך הבא לדף הלימוד
<BR><HR>
