<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 6/17/15
 * Time: 9:11 AM
 */
use ZfcUser\View\Helper\ZfcUserIdentity;
?>
שלום <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> !<br>
<div ng:controller="getChatters">
    <span ng-init="myself.id='<?php echo $this->zfcUserIdentity()->getId() ?>'"></span>
    <span ng-init="myself.nick='<?php echo $this->zfcUserIdentity()->getDisplayname() ?>'"></span>
    <span ng-init="myself.email='<?php echo $this->zfcUserIdentity()->getEmail() ?>'"></span>
    <span ng-init="myself.username='<?php echo $this->zfcUserIdentity()->getUsername() ?>'"></span>
    <span id="myself">
        ID: {{ myself.id }}  Username: {{ myself.username }} Nick: {{myself.nick}} Email: {{myself.email}}
    </span>
</div>
ברוך הבא לדף הלימוד
<BR><HR>
רשימת חברים מחוברים<br>
<ul ng:controller="getChatters">
    <span ng-init="myself.id='<?php echo $this->zfcUserIdentity()->getId() ?>'"></span>
    <span ng-init="myself.nick='<?php echo $this->zfcUserIdentity()->getDisplayname() ?>'"></span>
    <span ng-init="myself.email='<?php echo $this->zfcUserIdentity()->getEmail() ?>'"></span>
    <span ng-init="myself.username='<?php echo $this->zfcUserIdentity()->getUsername() ?>'"></span>
    <li ng:repeat="user in users">
        <span id="others"> ID: {{ user.id }} Username: {{ user.username }} Nick: {{user.nick}} Email: {{user.email}}</span>
    </li>
</ul>
