<?php
$this->headTitle("Add new account");

$css = "label { min-width: 100px; }";
$this->headStyle()->appendStyle($css);
?>

<h1>Add new account</h1>

<section class='light first last'>
<?php
$form->setAttributes( array('action'=>$this->url('account_add'), 'method'=>'post', 'name'=>'acount_add'));
$this->formElementErrors()->setAttributes(array('class'=>'error'));

echo $this->form()->openTag($form);
?>

    <?php echo $this->formElementErrors($form->get('name')); ?>
    <p><?php echo $this->formLabel($form->get('name')); ?><?php echo $this->formInput($form->get('name')); ?></p>
    <?php echo $this->formElementErrors($form->get('email')); ?>
    <p><?php echo $this->formLabel($form->get('email')); ?><?php echo $this->formInput($form->get('email')); ?></p>
    <?php echo $this->formElementErrors($form->get('max_users')); ?>
    <p><?php echo $this->formLabel($form->get('max_users')); ?><?php echo $this->formInput($form->get('max_users')); ?></p>
    <?php echo $this->formElementErrors($form->get('max_groups')); ?>
    <p><?php echo $this->formLabel($form->get('max_groups')); ?><?php echo $this->formInput($form->get('max_groups')); ?></p>
    <?php echo $this->formElementErrors($form->get('status')); ?>
    <p><?php echo $this->formLabel($form->get('status')); ?>
        <?php echo $this->formSelect($form->get('status')); ?></p>
    <p><?php echo $this->formInput($form->get('update')); ?></p>
<?php
echo $this->formInput($form->get('id'));
echo $this->form()->closeTag();
?>
</section>
