<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Service\AuthUserDetails'    => __DIR__ . '/Service/AuthUserDetails.php',
    'Application\Service\UserAccessChecker'  => __DIR__ . '/Service/UserAccessChecker.php',
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Users'                                  => __DIR__ . '/src/Application/model/Users.php',
);
