<?php
// Set the page title
$this->headTitle('Update Password');

$css = "label { min-width: 100px; }";
$this->headStyle()->appendStyle($css);
?>

<h3>Update Password</h3>

<section class='light first last'>
    <?php
    if ($this->flashMessenger()->hasMessages()) {
        echo $this->htmlList($this->flashMessenger()->getMessages(), false, array('class'=>'message'));
    }
    $this->formElementErrors()->setAttributes(array('class'=>'error'));
    echo $this->formElementErrors($form);
    echo $this->form()->openTag($form);
    ?>
        <p><?php echo $this->formLabel($form->get('password')); ?><?php echo $this->formInput($form->get('password')); ?></p>
        <p><?php echo $this->formLabel($form->get('password2')); ?><?php echo $this->formInput($form->get('password2')); ?></p>
        <p><?php echo $this->formInput($form->get('update')); ?></p>
    <?php echo $this->form()->closeTag(); ?>
</section>