<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authenticate\V1\Rpc\SetPassword\SetPasswordController'                     => __DIR__ . '/V1/Rpc/SetPassword/SetPasswordController.php',
    'Authenticate\V1\Rpc\SetPassword\SetPasswordControllerFactory'              => __DIR__ . '/V1/Rpc/SetPassword/SetPasswordControllerFactory.php',
    'Authenticate\V1\Rpc\ResetPassword\ResetPasswordController'                 => __DIR__ . '/V1/Rpc/ResetPassword/ResetPasswordController.php',
    'Authenticate\V1\Rpc\ResetPassword\ResetPasswordControllerFactory'          => __DIR__ . '/V1/Rpc/ResetPassword/ResetPasswordControllerFactory.php',
    'Authenticate\V1\Rpc\SendPasswordReset\SendPasswordResetController'         => __DIR__ . '/V1/Rpc/SendPasswordReset/SendPasswordResetController.php',
    'Authenticate\V1\Rpc\SendPasswordReset\SendPasswordResetControllerFactory'  => __DIR__ . '/V1/Rpc/SendPasswordReset/SendPasswordResetControllerFactory.php',
    'Authenticate\V1\Rpc\SetGarden\SetGardenController'                         => __DIR__ . '/V1/Rpc/SetGarden/SetGardenController.php',
    'Authenticate\V1\Rpc\SetGarden\SetGardenControllerFactory'                  => __DIR__ . '/V1/Rpc/SetGarden/SetGardenControllerFactory.php',
    'Authenticate\V1\Rpc\Logout\LogoutControllerFactory'                        => __DIR__ . '/V1/Rpc/Logout/LogoutControllerFactory.php',
    'Authenticate\V1\Rpc\Logout\LogoutController'                               => __DIR__ . '/V1/Rpc/Logout/LogoutController.php',
    'Authenticate\V1\Rpc\Login\LoginController'                                 => __DIR__ . '/V1/Rpc/Login/LoginController.php',
    'Authenticate\V1\Rpc\Login\LoginControllerFactory'                          => __DIR__ . '/V1/Rpc/Login/LoginControllerFactory.php',
    'Authenticate\Module'                                                       => __DIR__ . '/Module.php',
    'Authenticate\V1\Service\ChangePassword'                                    => __DIR__ . '/V1/Service/ChangePassword.php',
    'Authenticate\V1\Service\SendPasswordReset'                                 => __DIR__ . '/V1/Service/SendPasswordReset.php',
);
