<?php
/* @var $group \BrainpopUser\Entity\Group */
/* @var $account \BrainpopUser\Entity\Account */

$this->headTitle("View {$group->getName()} group details");
$this->headStyle()->appendStyle('label { min-width: 100px; }');

$delete_group_url    = $this->url('group_delete', array('group_id'=>$group->getId()));
$view_account_url   = $this->url('account_view', array('account_id'=>$group->getAccountId()));
?>

<section>
    <h1>Group: <?php echo "{$group->getName()}"; ?>&nbsp;
        <a href="<?php echo $delete_group_url; ?>" class="confirm" data-confirm-message='Are you sure you want to delete the group <?php echo $group->getName(); ?>?'><img src="/images/trash_white.png" alt='delete user'></a>
    </h1>
    <h3>Account: <a href="<?php echo $view_account_url; ?>"><?php echo $account->getName(); ?></a></h3>
</section>

<section class='light first last'>
    <?php
    if ($this->flashMessenger()->hasMessages()) {
        echo $this->htmlList($this->flashMessenger()->getMessages(), false, array('class'=>'message'));
    }

    $form->setAttributes( array('action'=>$this->url('group_update'), 'method'=>'post', 'name'=>'group_update'));
    $this->formElementErrors()->setAttributes(array('class'=>'error'));
    echo $this->form()->openTag($form);
    ?>

        <?php echo $this->formElementErrors($form->get('name')); ?>
        <p><?php echo $this->formLabel($form->get('name')); ?><?php echo $this->formInput($form->get('name')); ?></p>
        <?php echo $this->formElementErrors($form->get('invites_bank')); ?>
        <p><?php echo $this->formLabel($form->get('invites_bank')); ?><?php echo $this->formInput($form->get('invites_bank')); ?></p>
        <p><?php echo $this->formInput($form->get('update')); ?></p>
    <?php
    echo $this->formInput($form->get('id'));
    echo $this->formInput($form->get('account_id'));
    echo $this->form()->closeTag();
    ?>
</section>

<section class='first last'>
    <h2>Users Association</h2>
    <?php
    if (count($this->users)) {
        echo $this->partial('brainpop-user/user/group_association', array('users' => $this->users, 'accountId' => $group->getAccountId(), 'groupId' => $group->getId()));
    }
    else {
        echo "<p>0 Users</p>";
    }
    ?>
</section>